import * as path from 'path';
import { Identity, InflectionPoint } from '../core/types';
import { createIdentity } from '../core/identity';
import { createInflectionPoint } from '../core/inflectionPoint';
import { DiscoveredFile } from '../core/fileDiscovery';

const AI_AGENT_INDICATORS: Array<{
  pattern: (filePath: string, content: string) => boolean;
  name: string;
  type: 'agent_identity' | 'mcp_server_identity';
  inflectionType: 'AGENT_IDENTITY_CREATED' | 'MCP_SERVER_CONFIGURED' | 'TOOL_ACCESS_GRANTED';
  severity: 'HIGH' | 'MODERATE' | 'LOW';
  description: (filePath: string) => string;
  recommendation: string;
}> = [
  {
    pattern: (p) => p.includes('/.cursor/') || p.includes('\\.cursor\\'),
    name: 'Cursor AI Agent',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'MODERATE',
    description: (p) => `Cursor AI agent configuration detected: ${p}`,
    recommendation: 'Document what permissions and file access Cursor has. Ensure AI-generated code requires human review before merging.',
  },
  {
    pattern: (p) => p.includes('/.claude/') || p.includes('\\.claude\\'),
    name: 'Claude AI Agent',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'MODERATE',
    description: (p) => `Claude AI agent configuration detected: ${p}`,
    recommendation: 'Review Claude agent permissions. Ensure CLAUDE.md instructions do not grant excessive repository access.',
  },
  {
    pattern: (p) => p.includes('/.continue/') || path.basename(p) === '.continue',
    name: 'Continue AI Agent',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'MODERATE',
    description: (p) => `Continue AI agent configuration detected: ${p}`,
    recommendation: 'Review Continue agent configuration. Document what tools and permissions the agent can use.',
  },
  {
    pattern: (p) => {
      const name = path.basename(p).toLowerCase();
      return name === 'copilot-instructions.md' || p.includes('/.github/copilot-instructions');
    },
    name: 'GitHub Copilot Agent',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'MODERATE',
    description: (p) => `GitHub Copilot instructions detected: ${p}`,
    recommendation: 'Review Copilot instructions. Ensure AI-generated suggestions are reviewed before merge.',
  },
  {
    pattern: (p, content) => {
      const name = path.basename(p).toLowerCase();
      return (
        name.startsWith('mcp') && name.endsWith('.json') ||
        name === '.mcp.json' ||
        (content.includes('"mcpServers"') || content.includes('"mcp_servers"'))
      );
    },
    name: 'MCP Server Configuration',
    type: 'mcp_server_identity',
    inflectionType: 'MCP_SERVER_CONFIGURED',
    severity: 'HIGH',
    description: (p) => `MCP (Model Context Protocol) server configuration detected: ${p}`,
    recommendation: 'Audit MCP server tool access. Each MCP server represents an identity that can execute actions. Ensure servers have minimum required tool access.',
  },
  {
    pattern: (p) => {
      const name = path.basename(p).toLowerCase();
      return name.endsWith('.prompt.md') || name.endsWith('.prompt');
    },
    name: 'AI Prompt File',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'LOW',
    description: (p) => `AI prompt file detected: ${p}`,
    recommendation: 'Review prompt files for any instructions that could grant AI agents unintended access or authority.',
  },
  {
    pattern: (p, content) => {
      const name = path.basename(p).toLowerCase();
      return (
        name.startsWith('.cortextrace') ||
        content.includes('cortextrace') ||
        p.includes('/.cortextrace')
      );
    },
    name: 'CorTexTrace Agent',
    type: 'agent_identity',
    inflectionType: 'AGENT_IDENTITY_CREATED',
    severity: 'LOW',
    description: (p) => `CorTexTrace AI agent configuration detected: ${p}`,
    recommendation: 'CorTexTrace is a known code trace tool. Document what access it has and ensure traces do not expose sensitive data.',
  },
];

const AI_CODE_MARKERS = [
  /generated by (claude|gpt|copilot|cursor|chatgpt|openai)/i,
  /co-authored-by.*claude/i,
  /co-authored-by.*copilot/i,
  /ai-generated/i,
];

export function detectAIAgents(
  files: DiscoveredFile[],
  fileContents: Map<string, string>
): { identities: Identity[]; inflectionPoints: InflectionPoint[] } {
  const identities: Identity[] = [];
  const inflectionPoints: InflectionPoint[] = [];
  const seen = new Set<string>();

  for (const file of files) {
    const content = fileContents.get(file.path) ?? '';

    for (const indicator of AI_AGENT_INDICATORS) {
      if (indicator.pattern(file.path, content)) {
        const dedupeKey = `${indicator.name}::${file.path}`;
        if (seen.has(dedupeKey)) continue;
        seen.add(dedupeKey);

        const identity = createIdentity({
          name: indicator.name,
          identityType: indicator.type,
          sourceSystem: 'filesystem',
          sourceFile: file.path,
          credentialTypes: [],
          riskTags: ['ai_agent', indicator.inflectionType.toLowerCase()],
          metadata: { detectorType: 'aiAgentDetector', configFile: file.path },
        });
        identities.push(identity);

        inflectionPoints.push(createInflectionPoint({
          type: indicator.inflectionType,
          severity: indicator.severity,
          identityId: identity.id,
          identityName: identity.name,
          description: indicator.description(file.path),
          recommendation: indicator.recommendation,
          sourceFile: file.path,
          metadata: { agentType: indicator.name },
        }));
      }
    }

    // AI_CODE_CHANGE_PATH: detect AI-generated code markers in any file
    if (content) {
      for (const marker of AI_CODE_MARKERS) {
        if (marker.test(content)) {
          const dedupeKey = `ai_code_marker::${file.path}`;
          if (!seen.has(dedupeKey)) {
            seen.add(dedupeKey);
            inflectionPoints.push(createInflectionPoint({
              type: 'AI_CODE_CHANGE_PATH',
              severity: 'LOW',
              description: `AI-generated code marker detected in ${file.path}`,
              recommendation: 'Ensure AI-generated code changes are reviewed by a human before merging to production.',
              sourceFile: file.path,
              metadata: { marker: content.match(marker)?.[0] },
            }));
          }
          break;
        }
      }
    }
  }

  // Also check for agent config in directory structure
  const agentDirs = ['.cursor', '.claude', '.continue', '.cortextrace'];
  const seenDirs = new Set<string>();
  for (const file of files) {
    for (const agentDir of agentDirs) {
      if (file.path.includes(`/${agentDir}/`) || file.path.includes(`\\${agentDir}\\`)) {
        const dirKey = `dir::${agentDir}`;
        if (!seenDirs.has(dirKey)) {
          seenDirs.add(dirKey);
          // Already handled by file-level detection above
        }
      }
    }
  }

  return { identities, inflectionPoints };
}
